### ISSUE TITLE
Pass variable in message

### ISSUE THREAD

**Issue by landsman** [mb2dev/github-action-comment-pull-request#4]
Hello @mb2dev

thanks for this Github Action!
I want's to use it as comment with URL deployed app which I have in variable.
So my step looking like this:

```
      - name: 'Comment a pull_request'
        uses: mb2dev/github-action-comment-pull-request@1.0.0
        with:
          message: "App running on: ${SERVICE_URL}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          reactions: "rocket"
```

But message was sent as string:
![image](https://user-images.githubusercontent.com/3184228/90890776-ec885000-e3ba-11ea-9715-7b6b18123657.png)

Do you have idea how to pass this variable?
