### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by DanielMartinus** [mb2dev/github-action-comment-pull-request#6]
Hey @mb2dev,

Thanks for creating this plugin. While trying to use this plugin it was a little unclear what to do with the versioning. The example on both the marketplace and in this readme say `use: ./` however, people will not have a copy of this plugin in their repo.

Perhaps you could update the example to:

## Example usage

````
on: [pull_request]

jobs:
    build:
        name: Comment a pull_request
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Comment a pull_request
              uses: ./
              with:
                message: "Hello, It's my first comment with Github action !"
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                reactions: "+1 | -1 | laugh | hooray | confused | heart | rocket | eyes"
````
